export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function CompanyLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {children}
      <p>layout3!!!</p>
    </div>
  );
}
